apiVersion: v1
kind: ReplicationController
metadata:
  name: nabu
spec:
  replicas: 5
  selector:
    name: nabu
  template:
    metadata:
      labels:
        name: nabu
    spec:
      nodeSelector:
        role: accessories
      containers:
        - name: nabu
          image: srnk.io/svcs/nabu:0.1
          imagePullPolicy: Always
          ports:
            - name: nabu-server
              hostPort: 6228
              containerPort: 6228
          env:
            - name: KUBERNETES_AUTH_TRYKUBECONFIG
              value: "false"
            - name: KUBERNETES_MASTER
              value: "https://10.101.0.1"
          command:
            - java
            - -server
            - -jar
            - /nabu.jar
